# ENGLISH _____________________________
  [Languages.en]
    lang = "한국어"
    LanguageCode = "ko"
    title = "라이트코인 - 오픈소스 P2P 디지털 화폐"
    weight = 7

  # Hero section
  [Languages.en.hero]
    title = "화폐거래를 위한 최고의 암호화폐"
    subtitle = "블록체인 기술을 기반으로 함"

  # Navigation
  [Languages.en.navigation]
    brand = "라이트코인"
    download = "다운로드"
    about = "라이트코인에 대해서"
    team = "팀"
    contact = "문의처"

    # postpended links
    [[menu.postpend]]
      url = "https://litecointalk.io/"
      name = "포럼"
      weight = 10


  # About section
  [Languages.en.about]
    enable = true
    title = "라이트코인이란?"
    subtitle = "라이트코인은 P2P 인터넷 화폐로 소량의 비용으로 전세계 사람들에게 보낼 수 있고, 즉각적으로 사용가능 하다. 라이트코인은 오픈 소스이며, 탈 중앙화 된 글로벌 지불 네트워크이다. 네트워크는 수학으로 안전화가 되어 있어 개개인이 그들의 자금을 관리할 수 있도록 한다. 라이트코인은 수학을 기반으로한 다른 화폐들 보다 더욱 빠른 거래 승인과 향상된 저장 효율성을 특징을 가지고 있다. 라이트코인은 많은 산업의 지원과, 거래량, 유동성으로 비트코인의 보완된 통화 매체로 입증되었다."

    [[Languages.en.about.row]]
      [[Languages.en.about.row.list]]
        icon = "fa-group"
        title = "커뮤니티"
        description =  '<p class="text-no-margin text-left text-muted">성장하고 있는 라이트코인 커뮤니티에서 관련 정보를 찾을 수 있음</p><ul class="text-muted text-left "> <li><a href="https://litecointalk.io">Litecoin Forums</a></li><li><a href="https://web.telegram.org/#/im?p=@Litecoin">Litecoin Telegram</a></li> <li><a href="http://www.reddit.com/r/litecoin">Reddit Litecoin</a></li> <li><a href="https://twitter.com/search?q=litecoin%20-bitcoin&amp;src=typd">Search for Users on Twitter</a></li> <li><a href="http://freenode.net/" rel="nofollow">IRC FreeNode</a> network channels <a href="http://webchat.freenode.net/?channels=litecoin" rel="nofollow">#litecoin</a> (for general users) and <a href="http://webchat.freenode.net/?channels=litecoin-dev" rel="nofollow">#litecoin-dev</a> (for developers).</li> </ul>'

      [[Languages.en.about.row.list]]
        icon = "fa-laptop"
        title = "자원"
        description = '라이트코인과 관련된 정보, 서비스, 거래소를 이 사이트에서 찾을 수 있음 <a href="http://litecoin.info">Litecoin Wiki</a>. <br> 최신 네트워크 통계를 찾을 수 있음 <a href="http://ltc.block-explorer.com/charts">Litecoin Block Explorer Charts</a>. <br> 라이트코인 코어 및 관련 프로젝트 소스코드가 있음 <a href="https://github.com/litecoin-project">GitHub</a>.'

      [[Languages.en.about.row.list]]
        icon = "fa-heart"
        title = "오픈소스 소프트웨어"
        description = "라이트코인은 소프트웨어를 운영, 수정, 복사하여 배포할 수 있는 MIT/X11 라이센스 아래의 오픈소스 소프트웨어 프로젝트로 당신의 선택에 따라 소프트웨어의 복사 및 수정이 가능하다. 이 소프트웨어는 바이너리와 그들에 상응하는 소스코드의 개인 검증을 허락하는 투명한 프로세스 하에 배포되었다."

    [[Languages.en.about.row]]
      [[Languages.en.about.row.list]]
        icon = "fa-link"
        title = "블록체인"
        description = "라이트코인 블록체인은 이의 대응관계에 있는 비트코인 보다 더 높은 거래량을 처리할 수 있다. 더욱 잦은 블록 생성으로 인해, 네트워크는 향후에도 소프트웨어 수정의 필요없이 더 많은 거래를 지지할 수 있다. <br /> 결과적으로, 판매자는 더욱 빠른 이체확인 시간을 얻을 수 있을 뿐만 아니라, 높은 가치의 아이템을 위한 더 많은 이체확인들을 기다릴 수 있는 능력을 가지고 있다."

      [[Languages.en.about.row.list]]
        icon = "fa-lock"
        title = "지갑 암호화"
        description = "지갑 암호화는 당신의 지갑을 안전하게 지켜주도록 하여, 당신이 거래내역과 잔고를 확인할 수 있으나, 라이트코인을 전송하기 전에는 반드시 당신의 비밀번호를 입력하는 것이 요구된다. <br /> 이는 라이트코인을 훔치는 바이러스와 트로젠 바이러스로 부터 지갑을 보호해줄 뿐만 아니라 금액을 이체하기 전 진정성 확인을 제공한다."

      [[Languages.en.about.row.list]]
        icon = "fa-money"
        title = "채굴 보상"
        description = "채굴자들은 현재 블록 한 개에 25개의 라이트코인을 보상받고 있고, 이는 4년 마다 대략 절반이 된다(4년에 840,000 블록). <br />라이트코인 네트워크는 8천4백만개의 라이트코인을 생산할 수 있도록 계획되어 있고, 이는 비트코인의 통화단위의 4배 많은 값이다."

  # download section
  [Languages.en.download]
    enable = true
    gpg = "GPG Signatures"
    download = "다운로드"
    source = "소스"
    releasenotes = "릴리즈 노트"
    upgradenotes = "업그레이드 노트"

    windows = "Window 용"
    mac = "Mac OS X 용"
    linux = "GNU/Linux 용"
    android = "Android 용 라이트코인"
    blackberry = "BlackBerry 용 라이트코인"
    electrum = "Electrum Litecoin"


  # Contact section
  [Languages.en.contact]
    enable = true
    title = "문의처"
    subtitle  = '라이트코인 프로젝트 개발팀과 이곳에서 연락할 수 있다. <a href="mailto:contact@litecoin.org">contact@litecoin.org</a>'


  # Footer section
  [Languages.en.footer]
    enable = true
    copyright = 'Copyright &copy; 2011-2016 Litecoin Project. All rights reserved.'
